### ISSUE TITLE
[Zigbee2MQTT] `rtscts` option is probably no longer required

### ISSUE THREAD

**Issue by DominikPalo** [electrolama/docs.electrolama.com#36]
[Your documentation ](https://electrolama.com/radio-docs/zigbee2mqtt/#configuration) says that it is required to put the `rtscts: false` directive under the `advanced` section in the Zigbee2MQTT settings:
```
serial:
  port: /dev/ttyUSB0  #(change this if it is different on your machine)
advanced:
  rtscts: false
```
But according to [the Zigbee2MQTT docs]( https://www.zigbee2mqtt.io/guide/configuration/adapter-settings.html), the `rtscts` option is under the `port` section (and it is even set to false by default).

I'm not sure if something has changed in the latest versions of Zigbee2MQTT, but it seems that setting the `rtscts` option explicitly is no longer needed  - or is there another undocumented `rtscts` option under the `advanced` section?

cc @Koenkk
